const BUCH_EINHEIT = {
Buch1:[],
Buch2:["Einheit1","Einheit2","Einheit3","Einheit4","Einheit5","Einheit6","Einheit7","Einheit8",],
Buch3:[],
};
const B2E1 = [
{chinese:"个性，性格",type:"nom",word:"die Persönlichkeit",plural:"o.Pl",example:"Ich mag die Persönlichkeit dieser Frau"},
{chinese:"外貌，外表",type:"nom",word:"das Aussehen",plural:"o.Pl",example:"Der Junge hat ein gutes Aussehen"},
{chinese:"人，任务",type:"nom",word:"die Person",plural:"die Personen",example:"Ich möchte bei Ihnen einen Tisch für drei Personen bestellen"},
{chinese:"描绘",type:"inf",word:"beschreiben",example:"Können Sie den Mann mal beschreiben?"},
{chinese:"长的",type:"adj",word:"lang",example:"Die Hose ist dem Kind zu lang"},
{chinese:"短的",type:"adj",word:"kurz",example:"Ich habe kurze Haare"},
{chinese:"黑色的，暗色的",type:"adj",word:"dunkel",example:"Kannst du das Licht anmachen? Es wird langsam dunkel"},
{chinese:"西装",type:"nom",word:"der Anzug",plural:"die Anzüge",example:"Der graue Anzug gefällt mir gut"},
{chinese:"友好的，亲切的",type:"adj",word:"freundlich",example:"Ich habe eine freundliche Lehrerin. Ich mag sie"},
{chinese:"有才智的，聪明的",type:"adj",word:"intelligent",example:"Das Kind ist intelligent und kann schon mit sechs Jahren gut rechnen"},
{chinese:"连衣裙",type:"nom",word:"das Kleid",plural:"die Kleider",example:"Im Kaufhaus hat sie ein Kleid gekauft"},
{chinese:"灰色的",type:"adj",word:"grau",example:"Er trägt einen grauen Anzug"},
{chinese:"绿色的",type:"adj",word:"grün",example:"Die grüne Farbe gefällt mir"},
{chinese:"棕色的",type:"adj",word:"braun",example:"Das Kind hat braune Augen und blonde Haare"},
{chinese:"黄色",type:"adj",word:"gelb",example:"Welcher Pullover gefällt dir? Der Gelbe oder der braune?"},
{chinese:"选择，选举",type:"inf",word:"wählen",example:"Wir haben Peter zum Klassensprecher gewählt"},
{chinese:"喜欢的老师",type:"nom",word:"der Lieblingslehrer",plural:"die Lieberlingslehrer",example:"Herr Maier ist mein Lieblingslehrer"},
{chinese:"历史，故事",type:"nom",word:"die Geschite",plural:"die Geschichten",example:"China ist ein altes Land und hat eine lange Geschichte"},
{chinese:"布置作业，放弃，托办",type:"trennv",word:"auf/geben",example:"Der Lehrer hat heute nicht viele Hausaufgabe aufgegeben"},
{chinese:"漂亮的",type:"adj",word:"hübsch",example:"Sarbine ist ein junge hübsche Frau"},
{chinese:"有趣的",type:"adj",word:"lustig",example:"Der Lehrer hat heute im Unterricht eine lustige Geschichte erzählt"},
{chinese:"耐心的",type:"adj",word:"geduldig",example:"Wenn die Schüler den Lehrer fragen, antwortet er ihnen geduldig"},
{chinese:"解决，解答",type:"inf",word:"lösen",example:"Wir haben das Problem schon gelöst"},
{chinese:"此外，除此之外",type:"adv",word:"zudem",example:"Ich habe heute viele Hausaufgaben, zudem muss ich noch die Mathematik wiederholen"},
{chinese:"信赖",type:"inf",word:"verlassen",example:"sich verlassen auf A/Heinz ist ein alter Freund von mir, und ich kann mich auf ihn verlassen"},
{chinese:"帮助",type:"nom",word:"die Hilfe",plural:"die Hilfen",example:"Ich danke Ihnen für Ihre Hilfe"},
{chinese:"分数，成绩",type:"nom",word:"die Note",plural:"die Noten",example:"Ich habe bei der Prüfung eine gute Note bekommen"},
{chinese:"谈吐",type:"inf",word:"reden",example:"Er hat heute viel über das Thema geredet"},
{chinese:"以为，认为，相信",type:"inf",word:"glauben",example:"Ich glaube, er ist nach Hause gefahren"},
{chinese:"专业",type:"nom",word:"das Fach",plural:"die Fächer",example:"Welches Fach studiert er?Physik oder Mathematik?"},
{chinese:"人",type:"nom",word:"der Mensch",plural:"die Menschen",example:"Er ist ein netter Mensch und hilft gerne den anderen"},
{chinese:"玩笑",type:"nom",word:"der Witz",plural:"die Witze",example:"Über seine lustigen Witze haben wir viel gelacht"},
{chinese:"题目，主题",type:"nom",word:"das Thema",plural:"die Themen",example:"Der Umweltschutz ist ein wichtiges Thema für uns alle"},
{chinese:"解释",type:"nom",word:"die Erklärung",plural:"die Erklärungen",example:"Warum kommt er wieder so spät?Hat er eine Erklärung dadfür"},
{chinese:"啤酒肚",type:"nom",word:"der Bierbauch",plural:"die Bierbäuche",example:"Wenn man viel Bier trinkt, bekommt man langsam einen Bierbauch"},
{chinese:"耐心",type:"nom",word:"die Geduld",plural:"o.Pl",example:"Ich habe schon zwei Stunden gewartet und er kommt immer noch nicht. Ich habe keine Geduld mehr"},
{chinese:"无聊的，没意思的",type:"adj",word:"langweilig",example:"Ich finde das Buch langweilig und möchte es nicht mehr lesen"},
{chinese:"公正的，公平的",type:"adj",word:"gerecht",example:"Ich habe einen gerechten Lehrer"},
{chinese:"大方的，慷慨的",type:"adj",word:"großzügig",example:"Meine Tante ist großzügig und lädt mich oft zum Essen ein"},
{chinese:"带来",type:"trennV",word:"mit/bringen",example:"Mein Vater hat eine Reise nach China gemacht und mir ein Geschenk mitgebracht"},
{chinese:"情绪，心境",type:"nom",word:"die Laune",plural:"die Launen",example:"Warum hast du heute so schlechte Laune? Was ist los mit dir"},
{chinese:"几个，多个",type:"pron",word:"mehrere",example:"Heute habe ich in der Stadt mehrere Bücher gekauft"},
{chinese:"机会",type:"nom",word:"die Chance",plural:"die Chancen",example:"Ich glaube, das ist eine gute Chance für dich"},
{chinese:"吸引人的",type:"adj",word:"attraktiv",example:"J [gen hat ein gutes Aussehen und ist ein  attraktiver Mensch"},
{chinese:"微笑",type:"inf",word:"lächeln",example:"Er lächelt nur und sagt nichts"},
{chinese:"填入，登记",type:"trennV",word:"ein/tragen",example:"Tragen Sie bitte Ihren Namen in die Liste ein"},
{chinese:"大衣，外套",type:"nom",word:"der Mantel",plural:"die Mäntel",example:"Es ist heute sehr kalt. Du musst dir einen warmen Mantel anziehen"},
{chinese:"女衬衣，女上衣",type:"nom",word:"die Bluse",plural:"die Blusen",example:"Die rote Bluse steht dem Mädchen sehr gut"},
{chinese:"裤子",type:"nom",word:"die Hose",plural:"die Hosen",example:"Die Hose passt mir nicht. Sie ist mir zu lang"},
{chinese:"理由，动机",type:"nom",word:"der Grund",plural:"die Gründe",example:"Aus welchem Grund machst du das"},
{chinese:"访问，客人",type:"nom",word:"der Besuch",plural:"die Besuche",example:"Ich habe heute Abend Besuch und kann nicht mit dir ins Kino gehen"},
{chinese:"忘记",type:"inf",word:"vergessen",example:"Ich habe seinen Namen vergessen"},
{chinese:"巧克力",type:"nom",word:"die Schokolade",plural:"die Schokoladen",example:"Das Kind isst gern Schokolade"},
{chinese:"小伙子，男孩",type:"nom",word:"der Junge",plural:"die Jungen",example:"Kennst du den Jungen dort?"},
{chinese:"太阳镜",type:"nom",word:"die Sonnenbrille",plural:"die Sonnenbrillen",example:"Im Sommer brauche ich eine Sonnebrille"},
{chinese:"类型",type:"nom",word:"der Typ",plural:"die Typen",example:"Ich mag ihn nicht. Er ist nicht mein Typ"},
{chinese:"穿戴",type:"trennV",word:"an/haben",example:"Was hat er heute an? Einen Pullover oder eine Jacke"},
{chinese:"T恤衫",type:"nom",word:"das T-Shirt",plural:"die T-Shirts",example:"Er trägt oft ein T-Shirt und sieht sportlich aus"},
{chinese:"班级",type:"nom",word:"die Klasse",plural:"die Klassen",example:"Unsere Klasse hat insgesamt 32 Schüler"},
{chinese:"金黄色的",type:"adj",word:"blond",example:"Sie hat lange blonde Haare"},
{chinese:"重量",type:"nom",word:"das Gewicht",plural:"die Gewichte",example:"Die Frau hat in letzter Zeit Gewicht verloren und ist schlank geworden"},
{chinese:"称……的重量",type:"inf",word:"wiegen",example:"Haben Sie den Koffer gewoden? Wie viel Kilo wiegt er?"},
{chinese:"高兴的，愉快的",type:"adj",word:"fröhlich",example:"Ich wünsche Ihnen ein fröhliches Neujahr und alles Gute !"},
{chinese:"坦率的，坦诚的",type:"adj",word:"offen",example:"Darf ich meine Meinung offen sagen?"},
{chinese:"身材，身形",type:"nom",word:"die Figur",plural:"die Figuren",example:"Die Frau ist schlank und hat eine schöne Figur"},
{chinese:"棕色头发的",type:"adj",word:"braunhaarig",example:"Wer ist der braunhaarige Mann? Kennst du ihn?"},
{chinese:"有些(代词)",type:"pron",word:"manch",example:"Ich habe manche Menschen nach ihrer Meinung gefragt. Sie haben mir gern geantwortet"},
{chinese:"少许，少量",type:"adv",word:"wenig",example:"Ich habe wenig Geld und kann das teure Wörterbuch nicht kaufen"},
{chinese:"注意",type:"inf",word:"achten",example:"achten auf/Wenn man über die Straße gehen will, muss man auf die Ampel achten"},
];
const B2E2 = [
{chinese:"欧洲",type:"nom",word:"das Europa",plural:"o.pl",example:"Spanien liegt im Süden Europas"},
{chinese:"联邦共和国",type:"nom",word:"die Bundesrepublik",plural:"o.Pl",example:"Dänemark ist ein Nachbarland nördlich der Bundesrepublik Deutschland"},
{chinese:"面积",type:"nom",word:"die Fläche",plural:"die Flächen",example:"Die Fläche der Wohnung beträgt 90 Quadratmeter"},
{chinese:"平方公里",type:"nom",word:"das Quadratkilometer",plural:"o.Pl",example:"Wie viele Einwohner wohnen auf jedem Quadratkilometer durchschnittlich"},
{chinese:"居民",type:"nom",word:"der Einwohner",plural:"die Einwohner",example:"Wie viele Einwohner hat Berlin?"},
{chinese:"延伸",type:"nom",word:"die Ausdehnung",plural:"die Ausdehnungen",example:"Die Ausdehnung des Landes von Nörden nach Süden beträgt 876 Kilometer"},
{chinese:"人口密度",type:"nom",word:"die Bevölkerungsdichte",plural:"die Bevölkerungsdichten",example:"Südchina hat hohe Bevölkerungsdichte"},
{chinese:"邻国",type:"nom",word:"das Nachbarland",plural:"die Nachbarländer",example:"Wissen Sie, welche Nachbarländer Deutschland hat?"},
{chinese:"中间",type:"nom",word:"die Mitte",plural:"die Mitten",example:"In der Mitte des Zimmers steht ein großer Tisch"},
{chinese:"联邦制国家",type:"nom",word:"der Bundesstaat",plural:"die Bundesstaaten",example:"Deutschland ist ein Bundesstaat"},
{chinese:"联邦州",type:"nom",word:"das Bundesland",plural:"die Bundesländer",example:"Bayern ist ein Bundesland Deutschlands"},
{chinese:"由……组成",type:"inf",word:"bestehen",example:"Unsere Klasse besteht aus 20 Studentinnen und 22 Studenten/ bestehen auf 坚持"},
{chinese:"丹麦",type:"das Dänemark",word:"o.Pl",example:"Er war zwei Wochen in Dänemark und hat dort Urlaub gemacht"},
{chinese:"荷兰",type:"nom",word:"die Niederlande",plural:"die Niederlande",example:"Der Rhein fließt durch die Niederlande in die Nordsee（只有复数形式）"},
{chinese:"比利时",type:"nom",word:"das Belgien",plural:"o.Pl",example:"Brpssel ist die Hauptstadt Belgiens"},
{chinese:"卢森堡",type:"nom",word:"das Luxemburg",plural:"o.Pl",example:"In Luxemburg sprechen manche Leute Deutsch"},
{chinese:"法国",type:"nom",word:"das Frankreich",plural:"o.Pl",example:"Der Wein kommt aus Frankreich"},
{chinese:"捷克的",type:"adj",word:"tschechisch",example:"Die tschechisch Bundesrepublik liegt ördlich von Deutschland"},
{chinese:"总计，总数为",type:"inf",word:"betragen",example:"Die Rechnung beträgt 56 Euro"},
{chinese:"比较",type:"nom",word:"der Vergleich",plural:"die Vergleiche",example:"Im Vergleich zu seinem Vater spricht der Sohn viel besser Deutsch"},
{chinese:"阿尔卑斯山脉",type:"nom",word:"die Alpen",plural:"die Alpen",example:"In Urlaub fahren wir dieses Jahr in die Alpen（Alpen只有复数形式）"},
{chinese:"低地",type:"nom",word:"das Tiefland",plural:"die Tiefländer",example:"Im Norden Deutschlands liegt das Norddeutsche Tiefland"},
{chinese:"平坦的",type:"adj",word:"flach",example:"Das Land in Norddeutschland ist flach"},
{chinese:"南方的",type:"adj",word:"südlich",example:"Die Stadt liegt südlich des Flusses"},
{chinese:"汉诺威",type:"nom",word:"Hannover",example:"Hannover ist die Hauptstadt des Bundeslandes Niedersachsen"},
{chinese:"多瑙河",type:"nom",word:"die Donau",plural:"o.Pl",example:"Die Donau, einer der größten Flüsse Europas, entspringt in Deutschland"},
{chinese:"山脉",type:"nom",word:"das Gebirge",plural:"die Gebirge",example:"Herr Maier möchte in Urlaub ins Gebirge fahren, aber seine Frau will an die See"},
{chinese:"楚格峰",type:"nom",word:"die Zugspitze",plural:"o.Pl",example:"Die Zugspitze ist der höhsten Berg Deutschlands"},
{chinese:"博登湖",type:"nom",word:"der Bodensee",plural:"o.Pl",example:"Konstanz ist ein deutsche Stadt am Bodensee"},
{chinese:"边界",type:"nom",word:"die Grenze",plural:"die Grenzen",example:"Der Rhein bildet hier ein natürliche Grenze zwischen Deutschland und Frankreich"},
{chinese:"莱茵河",type:"nom",word:"der Rhein",plural:"o.Pl",example:"Man muss unbedingt ein Schifffahrt auf dem Rhein machen, wenn man in Deutschland ist"},
{chinese:"易北河",type:"nom",word:"die Elbe",plural:"o.Pl",example:"Die zweitgrößte deutsche Stadt Hamburg liegt an der Elbe"},
{chinese:"流淌",type:"inf",word:"fließen",example:"Der Chang Jiang fießt von Westen nach Osten"},
{chinese:"气候",type:"nom",word:"das Klima",plural:"o.Pl",example:"Wie ist das Klima in ihrem Land"},
{chinese:"平均的",type:"adj",word:"durchschnittlich",example:"Im Sommer haben wir hier ein durchschnittliche Temperatur von 28 Grad"},
{chinese:"温度",type:"nom",word:"die Temperatur",plural:"die Temperaturen",example:"Die Temperatur ist um 5 Grad gestiegen"},
{chinese:"度",type:"nom",word:"der Grad",plural:"die Grad",example:"Heute haben wir 23 Grad Celsius"},
{chinese:"摄氏",type:"nom",word:"Celsius",plural:"o.Pl",example:"Heute liegt die Temperatur zwischen 20 und 25 Grad Celsius"},
{chinese:"平均",type:"nom",word:"der Durchschnitt",plural:"die Durchschnitte",example:"Ich schlafe im Durchschnitt 7 Stunden pro Tag"},
{chinese:"下雨",type:"inf",word:"regnen",example:"Es hat gestern Abend stark geregnet"},
{chinese:"照耀，似乎，看来",type:"inf",word:"scheinen",example:"Die Sonne scheint und es ist schönes Wetter"},
{chinese:"雪",type:"nom",word:"der Schnee",plural:"o.Pl",example:"In seinem Leben hat er noch nie Schnee gesehen"},
{chinese:"工业区",type:"nom",word:"das Industriegebiet",plural:"die Industriegebiete",example:"Das Ruhrgebiet war eine wichtiges Industriegebiet Deutschlands"},
{chinese:"密集的",type:"nom",word:"dicht",example:"Wegen des dichten Verkehrs am Morgen kann er nicht pünktlich in die Firma kommen"},
{chinese:"微小的，很少的",type:"adj",word:"gering",example:"Der Unterschied zwiesch diesen zwei Gebieten ist gering"},
{chinese:"欧洲的",type:"adj",word:"europäisch",example:"Das europäische Essen schmeckt ihm sehr gut"},
{chinese:"结婚",type:"inf",word:"heiraten",example:"Vor einem Jahr hat sie Peter geheiratet"},
{chinese:"大约",type:"adv",word:"ungefähr",example:"Auf die Party sind ungefähr 30 Leute gekommen"},
{chinese:"比较",type:"inf",word:"vergleichen",example:"Wir haben heute im Unterricht Deutschland mit Frankreich verglichen"},
{chinese:"母语",type:"nom",word:"die Muttersprache",plural:"die Muttersprachen",example:"Chinesisch ist meine Muttersprache"},
{chinese:"列支敦士登",type:"nom",word:"das Liechtenstein",plural:"o.Pl",example:"Liechtenstein ist ein kleines Land"},
{chinese:"部分",type:"nom",word:"der Teil",plural:"die Teile",example:"Ich habe nur einen Teil des Textes verstanden"},
{chinese:"瑞士人",type:"nom",word:"der Schweizer",plural:"die Schweizer",example:"Er ist Schweizer und wohnt in Bern"},
{chinese:"边境地区",type:"nom",word:"das Grenzgebiet",plural:"die Grenzgebirte",example:"Er wohnt im Granzgebirt und spricht zwei Sprachen"},
{chinese:"说德语的",type:"adj",word:"deutschsprachig",example:"Österreich ist ein deutschsprachiges Land"},
{chinese:"少数",type:"nom",word:"die Minderheit",plural:"die Minderheiten",example:"Nur ein Minderheit ist gegen diese Politik"},
{chinese:"罗马尼亚",type:"nom",word:"das Rumänien",plural:"o.Pl",example:"Seine Eltern hat lange in Romänien gewohnt"},
{chinese:"中心的",type:"adj",word:"zentral",example:"Das Haus ist zentral"},
{chinese:"中转国家",type:"nom",word:"das Transitland",plural:"die Transitländer",example:"Die Schweiz ist ein Transitland"},
{chinese:"交错",type:"inf",word:"kreuzen",example:"Zwei Strißen kreuzen sich hier"},
{chinese:"官方的",type:"inf",word:"offiziell",example:"Das war eine offizielle Erklärung"},
{chinese:"变换，更换",type:"inf",word:"wechseln",example:"Er möchte zuerst in die Bank gehen und Geld wechseln"},
{chinese:"最少，最低",type:"adv",word:"zumindest",example:"In Deutschland studiert ein Student an der Universität zumindest 4 Jahre"},
{chinese:"产品",type:"nom",word:"das Produkt",plural:"die Produkte",example:"Das Auto ist ein deutsches Produkt"},
{chinese:"文件，文献",type:"nom",word:"das Dokument",plural:"die Dokumente",example:"Er muss dieses Dokument ins Deutsch übersetzen"},
{chinese:"支出",type:"trennV",word:"aus/geben",example:"Wie viel Geld geben Sie im Monat für das Essen aus"},
{chinese:"伯尔尼",type:"nom",word:"das Bern",plural:"o.Pl",example:"Bern ist die Hauptstadt der Schweiz"},
{chinese:"苏黎世",type:"nom",word:"das Zürich",plural:"o.Pl",example:"Zürich ist eine große Stadt"},
{chinese:"日内瓦",type:"nom",word:"das Genf",plural:"o.Pl",example:"In Genf spricht man Fraozösisch"},
{chinese:"休养之地",type:"nom",word:"der Erholungsort",plural:"die Erholungsorte",example:"Im Urlaub möchte sie in einen Erholungsort fahren und sich erholen"},
{chinese:"体验设施",type:"nom",word:"die Sportanlage",plural:"die Sportanlagen",example:"Die Stadt hat viele schöne Sportanlagen gebaut"},
{chinese:"建造",type:"inf",word:"bauen",example:"Man hat das Haus vor 50 Jahren gebaut"},
{chinese:"骄傲的",type:"adj",word:"stolz",example:"Ich bin sehr stolz auf meine Arbeit"},
{chinese:"登山铁道",type:"nom",word:"die Bergbahn",plural:"die Bergbahnen",example:"Wir können mit der Bergbahn auf den Berg fahren"},
{chinese:"偏好",type:"nom",word:"die Vorliebe",plural:"o.Pl",example:"Ich trinke mit Vorliebe grünen Tee"},
{chinese:"电视节目",type:"nom",word:"das TV-Programm",plural:"die TV-Programme",example:"Ich finde einige TV-Programme lanweilig"},
{chinese:"发源于",type:"inf",word:"entspringen",example:"Die Donau entspringt in Deutschland"},
{chinese:"信息，资料",type:"nom",word:"die Information",plural:"die Informationen",example:"Wo finde ich Informationen über diese Stadt"},
];
const B2E3 = [
{chinese:"富于想象的",type:"adj",word:"phantasievoll",example:"Die Amerikaner sind phantasievoll"},
{chinese:"准时的",type:"adj",word:"pünklich",example:"Die Deutschen sind pünktlich"},
{chinese:"保守的",type:"adj",word:"konservativ",example:"Die Chinesen sind konservativ"},
{chinese:"乐于助人的",type:"adj",word:"hilfsbereit",example:"Frau Li ist immer hilfsbereit"},
{chinese:"整齐的",type:"adj",word:"ordentlich",example:"Das Zimmer von Monika ist ordentlich"},
{chinese:"幽默的",type:"adj",word:"humorvoll",example:"Unser Deutschlehrer ist sehr humorvoll"},
{chinese:"干净",type:"nom",word:"die Sauberkeit",plural:"o.Pl",example:"Achten Sie auf die Sauberkeit"},
{chinese:"准确性",type:"nom",word:"die Genauigkeit",plural:"o.Pl",example:"Die Genauigkeit ist wichtig"},
{chinese:"干净的，整洁的",type:"adj",word:"sauber",example:"Dein Zimmer ist sehr sauber"},
{chinese:"交通规则",type:"nom",word:"die Verkehrsregel",plural:"die Verkehrsregeln",example:"Mann soll auf die Verkehrsregeln achten"},
{chinese:"注意，重视",type:"inf",word:"beachten",example:"Beachten Sie auf die Regeln hier"},
{chinese:"遵守",type:"trennV",word:"an/halten",example:"Wir sollen uns an die Besuchszeit anhalten"},
{chinese:"迟到",type:"inf",word:"verspäten",example:"Ich habe mich leider etwas verspätet"},
{chinese:"平等权利",type:"nom",word:"die Gleichberechtigung",plural:"o.Pl",example:"Man und Frau sind gleichberechtigt"},
{chinese:"对……感兴趣",type:"inf",word:"interessieren",example:"Wir interesieren uns für Deutsch"},
{chinese:"目光",type:"nom",word:"der Blick",plural:"die Blicke",example:"Liebe auf den ersten Blick"},
{chinese:"拉，吸入，移动，迁移",type:"inf",word:"ziehen",example:"Ziehen Sie bitte die Tür"},
{chinese:"有自信的",type:"adj",word:"selbstbewusst",example:"Xiao Li sieht sehr selbstbewusst aus"},
{chinese:"惊讶的",type:"adj",word:"erstaunt",example:"Ich bin erstaunt darüber, dass er so etwas sagt"},
{chinese:"烧酒",type:"nom",word:"der Schnaps",plural:"die Schnäpse",example:"Sein Onkel trinkt gern Schnaps"},
{chinese:"不久前",type:"adv",word:"kürzlich",example:"Kürzlich habe ich eine E-Mail von meinem Fraund bekommen"},
{chinese:"南美人",type:"nom",word:"der Südamerikaner",plural:"die Südamerikaner",example:"Ronaldo ist Südamerikaner"},
{chinese:"而是",type:"konj",word:"sondern",example:"Das ist kein Wecker, sondern eine Uhr"},
{chinese:"情绪，气氛",type:"nom",word:"die Stimmung",plural:"die Stimmungen",example:"Gabi ist in guter Stimmung"},
{chinese:"放松的，松弛的",type:"adj",word:"locker",example:"Um locker zu werden, will er heute Abend nur fernsehen"},
{chinese:"偏见，成见",type:"nom",word:"das Vorurteil",plural:"die Vorurteile",example:"Manche Deutsche haben Vorurteile gegenüber Ausländern"},
{chinese:"对外国人不友好的",type:"adj",word:"ausländerfeindlich",example:"Die meisten Deutschen sind nicht ausländerfeindlich"},
{chinese:"夺走，夺取",type:"trennV",word:"weg/nehmen",example:"Er hat mir das Geld weggenommen"},
{chinese:"宗教",type:"nom",word:"die Religion",plural:"die Religionen",example:"Jede Nationalität hat ihre eigene Religion"},
{chinese:"富有的，丰富的",type:"adj",word:"reich",example:"Thomas ist sehr reich"},
{chinese:"可靠的",type:"adj",word:"zuverlässig",example:"Er ist zuverlässig"},
{chinese:"有环保意识的",type:"adj",word:"umweltbewusst",example:"Sie ist umweltbewusst"},
{chinese:"尝试",type:"inf",word:"versuchen",example:"Versuch noch mal, diesen deutschen Text ins Chinesiche zu übersetzen"},
{chinese:"相关的，相应的",type:"adj",word:"entsprechend",example:"Zu dieser Meinung sucht er entsprechendes Beispiel"},
{chinese:"严肃的，认真的",type:"adj",word:"ernst",example:"Er ist oft ernst"},
{chinese:"愿望，意愿",type:"nom",word:"der Wunsch",plural:"die Wünsche",example:"Welche Wünsche hast du?"},
{chinese:"同事",type:"nom",word:"der Kollege",plural:"die Kollegen",example:"Herr Li ist mein Kollege"},
{chinese:"联系，接触",type:"nom",word:"der Kontakt",plural:"die Kontakte",example:"Bleiben wir in Kontakt"},
{chinese:"流行的",type:"adj",word:"üblich",example:"Wir arbeiten nach der üblichen Methode"},
{chinese:"收入",type:"nom",word:"das Einkommen",plural:"die Einkommen",example:"Man darf nicht nach dem Einkommen fragen"},
{chinese:"游泳",type:"inf",word:"schwimmen",example:"Das Kind kann schwimmen"},
{chinese:"复习",type:"inf",word:"wiederholen",example:"Ich habe die Vokabeln wiederholt"},
{chinese:"对……作准备",type:"trennV",word:"vor/bereiten",example:"Wir bereiten uns nun auf die Prüfung vor"},
{chinese:"奖学金",type:"nom",word:"das Stipendium",plural:"die Stipendien",example:"Er hat ein Stipendium von der Uni. bekommen"},
{chinese:"逗留",type:"nom",word:"der Aufenthalt",plural:"die Aufenthalte",example:"Während des Aufenthalts in China habe ich viel gesehen"},
{chinese:"可能性",type:"nom",word:"die Möglichkeit",plural:"die Möglichkeiten",example:"Gibt es eine Möglichkeit, dort zu jobben"},
{chinese:"手续",type:"nom",word:"die Formalität",plural:"die Formalitäten",example:"Die Formalitäten sind schon fertig"},
{chinese:"计划，打算",type:"nom",word:"der Plan",plural:"die Pläne",example:"Welchen Plan hast du？"},
{chinese:"义务，责任",type:"nom",word:"die Pflicht",plural:"die Pflichten",example:"Wir haben die Pflicht, den anderen zu helfen"},
{chinese:"办好，完成",type:"inf",word:"erledigen",example:"Vor der Abreise ins Ausland soll man zuerst die Formalitäten erledigen"},
{chinese:"派遣，寄",type:"inf",word:"schicken",example:"Er hat ein Paket geschickt"},
{chinese:"用电话的",type:"adj",word:"telefonisch",example:"Ich habe ihn telefonisch erreicht"},
{chinese:"到达，联系上",type:"inf",word:"erreichen",example:"In wenigen Minuten erreichen wir München"},
{chinese:"提高，改善",type:"inf",word:"verbessern",example:"Ich möchte mein Deutsch verbessern"},
{chinese:"表达",type:"trennV",word:"aus/drucken",example:"Ich habe meine Meinung ausgedruckt"},
{chinese:"打算，目的",type:"nom",word:"die Absicht",plural:"die Absichten",example:"Er sagt das ohne Absicht"},
{chinese:"打算做",type:"trennV",word:"vor/nehmen",example:"Ich nehme mir vor, an diesem Wochenende nach Shanghai zu fahren"},
{chinese:"野餐",type:"nom",word:"das Picknick",plural:"die Picknicks",example:"Wir machen morgen ein Picknick"},
{chinese:"长篇小说",type:"nom",word:"der Roman",plural:"die Romane",example:"Welchen Roman liest du zurzeit"},
{chinese:"归还",type:"trennV",word:"zurück/geben",example:"Wann gibst du mir das Buch zurück"},
{chinese:"影响，打搅",type:"inf",word:"stören",example:"Bitte störe mich nicht"},
{chinese:"语音实验室",type:"nom",word:"das Sprachlabor",plural:"die Sprachlabors",example:"Morgen haben wir Unterricht im Sprachlabor"},
{chinese:"好奇的",type:"adj",word:"neugierig",example:"Sei nicht zu neugierig"},
{chinese:"小酒馆",type:"nom",word:"die Kneipe",plural:"die Kneipen",example:"Die Kneipe ist gleich gegenüber der Post"},
{chinese:"变化",type:"inf",word:"verändern",example:"China hat sich in den Letzten Jahren sehr viel verändert"},
{chinese:"自己的",type:"adj",word:"eigen",example:"Jetzt hat er sein eigenes Auto"},
{chinese:"真的",type:"adj",word:"wahr",example:"Er kommt heute. Ist es wahr"},
{chinese:"开始",type:"nom",word:"der Anfang",plural:"die Anfänge",example:"Am Anfang habe ich ihn nicht verstanden"},
{chinese:"年轻人",type:"nom",word:"der Jugendliche",plural:"die Jugendlichen",example:"Viele chinesische Jugentliche wollen Deutsch lernen"},
{chinese:"流行音乐",type:"nom",word:"die Popmusik",plural:"o.Pl",example:"Sein Soh hört gern Popmusik"},
{chinese:"竞争",type:"nom",word:"die Konkurrenz",plural:"die Konkurrenzen",example:"Sie steht mit Anna in Konkurrenz"},
{chinese:"举行，发送",type:"trennV",word:"statt/finden",example:"Die Vorlesung findet um 9 Uhr statt"},
{chinese:"纠正，改正",type:"inf",word:"korrigieren",example:"Der Lehrer korriegiert den Text"},
{chinese:"漂亮的",type:"adj",word:"schick",example:"Sie trägt eine schicke Jacke"},
{chinese:"人口总数",type:"nom",word:"die Gesamtbevölkerung",plural:"die Gesamtbevölkerungen",example:"Die Gesamtbevökerung von China beträgt über 13 Milliarden"},
{chinese:"公民，市民",type:"nom",word:"Büger",plural:"die Büger",example:"Ich bin nur ein einfacher Bürger"},
{chinese:"很多的，许多的",type:"adj",word:"zahlreich",example:"In der Bibliothek gibt es zahlreiche Bücher"},
{chinese:"主要的，占优势的",type:"adj",word:"vorwiegend",example:"Morgen ist es vorwiegend heiter"},
{chinese:"以下的，如下的",type:"adj",word:"folgend",example:"Er hat folgende Meinung ausgedrückt"},
{chinese:"民意测试",type:"nom",word:"die Umfrage",plural:"die Umfragen",example:"Er hat eine Umfrage über Deutschlernen unter den Studenten gemacht"},
{chinese:"西班牙",type:"nom",word:"das Spanien",plural:"o.Pl",example:"Er kommt aus Spanien"},
{chinese:"和某人合得来",type:"trennV",word:"aus/kommen",example:"Gabi kommt mit ihren Eltern sehr gut aus"},
{chinese:"音乐会",type:"nom",word:"das Konzert",plural:"die Konzerte",example:"Wir gehen heute Abend ins Konzent"},
{chinese:"得知，经历",type:"inf",word:"erfahren",example:"Wir haben von der traurigen Nachricht erfahren"},
{chinese:"这样的",type:"solch",word:"pron",example:"Es ist herrlich, bei solchem Wetter einen Ausflug zu machen"},
{chinese:"不同的",type:"adj",word:"anders",example:"Sie siehr anders als ihre Schwester"},
{chinese:"奇怪的",type:"adj",word:"komisch",example:"Er trägt heute ein komische Mütze"},
{chinese:"社会的",type:"adj",word:"sozial",example:"Das ist ein soziales Problem"},
{chinese:"保障，保护",type:"nom",word:"der Schutz",plural:"o.Pl",example:"Jeder soll auf Umweltschutz achten"},
{chinese:"冲突，纠纷",type:"nom",word:"der Konflikt",plural:"die Konflikte",example:"Zwischen Jungen und Alten gibt es Konflikte"},
{chinese:"出现，产生",type:"inf",word:"entstehen",example:"1949 entstanden zwei deutsche Staaten: die BRD und die DDR"},
{chinese:"民族",type:"nom",word:"die Nationalität",plural:"die Nationalitäten",example:"Jede Nationalität hat ihre eigene Kutur"},
{chinese:"社会，团体",type:"nom",word:"die Gesellschaft",plural:"die Gesellschaften",example:"Es ist schön, dass es in unserer Gesellschaft viele Ausländer gibt"},
{chinese:"极好的",type:"adj",word:"wunderbar",example:"In dieser Zeit haben wir wunderbares Wetter"},
{chinese:"发展，提高",type:"nom",word:"die Entwicklung",plural:"die Entwicklungen",example:"die wirtschaftliche Entwicklung Chinas ist ganz schnell"},
{chinese:"为……贡献",type:"trennV",word:"bei/tragen",example:"Die Ausländer haben viel zur Entwicklung Deutschlands beigetragen/ zu D bei/tragen"},
{chinese:"请求",type:"inf",word:"bitten",example:"Ich bitte ihn um Hilfe/ bitten A um etw"},
];
const B2E4 = [
{chinese:"狼",type:"nom",word:"der Wolfe",plural:"die Wölfe",example:"Der Wolf wollte das Schwein fressen"},
{chinese:"小山羊",type:"nom",word:"das Geißlein",plural:"die Geißlein",example:"Die Geißlein mussten zu Haus bleiben"},
{chinese:"白雪公主",type:"nom",word:"das Schneewittchen",example:"Hast du ,, das Schneewittchen\" gelesen"},
{chinese:"皇帝",type:"nom",word:"der Kaiser",plural:"die Kaiser",example:"Weißt du, wie viele Kaiser es in der Qing-Dynastie gab"},
{chinese:"小红帽",type:"nom",word:"das Rotkäppchen",example:"Rotkäppchen ist ein süßes Mädchen"},
{chinese:"童话",type:"nom",word:"das Märchen",plural:"die Märchen",example:"Gebrüder Grimm schrieben viele bekannte Märchen"},
{chinese:"(雌)山羊",type:"nom",word:"die Geiß",plural:"die Geißen",example:"Die alte geiße fand ihre Kinder nicht"},
{chinese:"木头",type:"nom",word:"das Holz",plural:"die Hölzer",example:"Dieser Schrank ist aus Holz"},
{chinese:"搜集，收集",type:"inf",word:"sammeln",example:"Ich sammle die Briefmarken"},
{chinese:"森林",type:"nom",word:"der Wald",plural:"die Wälder",example:"Der Vater ging in den Wald"},
{chinese:"敲门",type:"inf",word:"klopfen",example:"Es klopfte an der Tür"},
{chinese:"声音",type:"nom",word:"die Stimme",plural:"die Stimmen",example:"Sie hat eine schöne Stimme"},
{chinese:"认识，认出",type:"inf",word:"erkennen",example:"Ich habe ihn kaum erkannt"},
{chinese:"粗的，粗野的",type:"adj",word:"grob",example:"Der Wolf hat eine grobe Stimme"},
{chinese:"短时间，片刻",type:"nom",word:"die Weile",plural:"die Weilen",example:"Ich bin erst vor einer Weile gekommen"},
{chinese:"（动物）吃",type:"inf",word:"fressen",example:"Der Tiger frisst Fleisch"},
{chinese:"粉笔",type:"nom",word:"die Kreide",plural:"die Kreiden",example:"Er schreibt das Wort mit einer Kreide an die Tafel"},
{chinese:"使优美，使精美",type:"inf",word:"verfeinern",example:"Sie verfeinert die Speise"},
{chinese:"门缝",type:"nom",word:"der Türspalt",plural:"die Türspalte",example:"Durch die Türspalt sahen die Geißen die schwarzen Füße des Wolfs"},
{chinese:"磨坊厂",type:"nom",word:"die Mühle",plural:"die Mühlen",example:"In der Mühle mahlt man Mehl"},
{chinese:"跳进来",type:"trennV",word:"herein/springen",example:"Der Wolf sprang ins Haus herein"},
{chinese:"可怜的，贫穷的",type:"adj",word:"arm",example:"Er ist aus einer armen Familie"},
{chinese:"躲藏",type:"inf",word:"verstecken",example:"Anna versteckt sich hinter der Tür/sich verstecken"},
{chinese:"奶锅",type:"nom",word:"der Milchtopf",plural:"die Milchtöpfe",example:"Die Mutter kocht Milch mit Milchtopf"},
{chinese:"睡着，入睡",type:"trennV",word:"ein/schlafen",example:"Gestern Nacht konnte ich nicht einschlafen"},
{chinese:"喊，叫",type:"inf",word:"rufen",example:"Die Mutter rief ihren Sohn: ,, Komm schnell \""},
{chinese:"到处",type:"adv",word:"überall",example:"Ich habe meinen Füller überall gesucht, aber nicht gefunden"},
{chinese:"走出来",type:"trennV",word:"heraus/kommen",example:"Das Geißlein kam aus dem Uhrenkasten heraus"},
{chinese:"发生",type:"inf",word:"geschehen",example:"Die Geschichte geschah vor 10 Jahren"},
{chinese:"移动，活动",type:"inf",word:"bewegen",example:"Die Erde bewegt sich um die Sonne"},
{chinese:"剪刀",type:"nom",word:"die Schere",plural:"die Scheren",example:"Sie schneidet den Stoff mit einer Schere"},
{chinese:"剪，裁",type:"trennV",word:"auf/schneiden",example:"Die alte Geiß schnitt den Wolfsbauch auf"},
{chinese:"一个接一个",type:"adv",word:"nacheinander",example:"Die Kinder kommen nacheinander aus dem Zimmer"},
{chinese:"活着的",type:"adj",word:"lebendig",example:"Der Fisch ist noch lebendig"},
{chinese:"石头",type:"nom",word:"der Stein",plural:"die Steine",example:"Steter Tropfen hölt den Stein"},
{chinese:"缝上",type:"trennV",word:"zu/nähen",example:"Die alte Geiß näht den Wolfsbauch wieder zu"},
{chinese:"睡醒",type:"trennV",word:"aus/schlafen",example:"Am Sonntag habe ich gut ausgeschlafen"},
{chinese:"口渴",type:"nom",word:"der Durst",plural:"o.Pl",example:"Das Kind hat großen Durst"},
{chinese:"井",type:"nom",word:"der Brunnen",plural:"die Brunnen",example:"Früher holte man Wasser aus dem Brunnen"},
{chinese:"拍，击打",type:"trennV",word:"sich zusammen/schlagen",example:"Er schlug die Hände zusammen"},
{chinese:"步伐",type:"nom",word:"der Schritt",plural:"die Schritte",example:"Gehen Sie noch ein paar Schritte weiter bitte"},
{chinese:"弯曲",type:"inf",word:"beugen",example:"Er aibeitet mit gebeugtem Rücken"},
{chinese:"把……拉下去",type:"trennV",word:"hinunter/ziehen",example:"Die Steine zogen den Wolf in den Brunnen hinunter"},
{chinese:"淹死",type:"inf",word:"ertrinken",example:"Der Wolf ertrank schließlich im Brunnen"},
{chinese:"跳来跳去",type:"trennV",word:"herum/tanzen",example:"Die Kinder tanzten um die Mutter herum"},
{chinese:"目标，目的",type:"nom",word:"das Ziel",plural:"die Ziele",example:"Ich versuche, mein Ziel zu erreichen"},
{chinese:"发生",type:"inf",word:"passieren",example:"Was ist passiert"},
{chinese:"把……叫作",type:"inf",word:"nennen",example:"Wir nennen ihn Hans"},
{chinese:"篮子",type:"nom",word:"der Korb",plural:"die Körbe",example:"Mit einem Korb ist sie zum Markt gegangen"},
{chinese:"满的",type:"adj",word:"voll",example:"Heute habe ich alle Hände voll zu tun"},
{chinese:"遇到，碰见",type:"inf",word:"begegnen",example:"Ich bin gestern meinem Freund begegnet"},
{chinese:"生气的",type:"adj",word:"böse",example:"Er ist böse auf mich"},
{chinese:"狡猾的",type:"adj",word:"listig",example:"Der Wolf war sehr listig"},
{chinese:"采，摘",type:"inf",word:"pflücken",example:"Das Rotkäppchen pflückt die Blumen"},
{chinese:"匆忙",type:"adj",word:"eilig",example:"Sie ging eilig weg"},
{chinese:"报告，演讲",type:"nom",word:"der Vortrag",plural:"die Vorträge",example:"Prof.Li hält einen Vortrag über den Umweltschutz"},
{chinese:"没有人",type:"pron",word:"niemand",example:"Niemand ist da"},
{chinese:"戴上",type:"trennV",word:"auf/setzen",example:"Sie setzte ihre Brille auf und ging aus"},
{chinese:"对……作反应",type:"inf",word:"reagieren",example:"Er reagiert auf meine Frage nicht"},
{chinese:"惊异的",type:"adj",word:"überrascht",example:"Ich war sehr überrascht, als ich das hörte"},
{chinese:"让，使",type:"inf",word:"lassen",example:"Der Lehrer lässt mich den Text lesen"},
{chinese:"幼儿园",type:"nom",word:"der Kindergarten",plural:"die Kindergärten",example:"Ihre Tochter besucht schon den Kindergarten"},
{chinese:"中学",type:"nom",word:"die Mittelschule",plural:"die Mittelschulen",example:"Sie besuchte jetzt die Mittelschule"},
{chinese:"结束",type:"inf",word:"beenden",example:"Wir müssen heute diese Arbeit beenden"},
{chinese:"飞机场",type:"nom",word:"der Flughafen",plural:"die Flughäfen",example:"Hans hat ein Taxi zum Flughafen genommen"},
{chinese:"随身携带",type:"trennV",word:"mit/nehmen",example:"Nimmst du das Buch mit"},
{chinese:"雨伞",type:"nom",word:"der Regenschirm",plural:"die Regenschirme",example:"Wo ist der Regenschirm"},
{chinese:"书店nom",type:"die Buchhandlung",word:"die Buchhandlungen",example:"Die Buchhandlung ist sehr groß"},
{chinese:"洗涤物",type:"nom",word:"die Wäsche",plural:"die Wäschen",example:"Gestern habe ich die Wäsche gewaschen"},
{chinese:"整理，收拾干净",type:"trennV",word:"auf/räumen",example:"Nach dem Essen räumt sie das Zimmer auf"},
{chinese:"寄走，寄出",type:"trennV",word:"ab/schicken",example:"Ich muss den Brief noch abschicken"},
{chinese:"命令，吩咐",type:"inf",word:"befehlen",example:"Befiehlst du sonst noch etwas"},
{chinese:"名人轶事",type:"nom",word:"die Anekdote",plural:"die Anekdoten",example:"Diese Anekdote ist hochinteressant"},
{chinese:"表扬",type:"inf",word:"loben",example:"Der Lehrer lobt diese fleißige Schülerin oft"},
{chinese:"敬（烟，酒，茶），供应",type:"trennV",word:"an/bieten",example:"Darf ich Ihnen eine Tasse Tee anbieten"},
{chinese:"把……放进衣袋",type:"trennV",word:"ein/stecken",example:"Er steckte den Brief in die Tasche ein"},
{chinese:"留下，保存",type:"inf",word:"behalten",example:"Wie lange kann ich das Buch behalten"},
{chinese:"纪念，会议",type:"nom",word:"die Erinnerung",plural:"die Erinnerungen",example:"Das ist ein schöne Erinnerung für mich"},
{chinese:"足够",type:"inf",word:"genüben",example:"Zwei Meter Stoff genügen für ein Kleid"},
{chinese:"重要的",type:"adj",word:"bedeutend",example:"China spielt eine bedeutende Rolle in der Welt"},
{chinese:"几乎不",type:"adv",word:"kaum",example:"Ich konnte ihn kaum erkennen"},
{chinese:"礼堂",type:"nom",word:"der Saal",plural:"die Säle",example:"Der Saal ist voll von Menschen"},
{chinese:"转向",type:"inf",word:"wenden",example:"Der Wind hat sich gewendet"},
{chinese:"观众",type:"nom",word:"der Zuschauer",plural:"die Zuschauer",example:"Im Theater gibt es viele Zuschauer"},
{chinese:"法国法郎",type:"nom",word:"der Franc",plural:"die Francs",example:"Das Hemd kostet 199 Francs"},
{chinese:"满的，拥挤的",type:"adj",word:"überfüllt",example:"Der Saal ist überfüllt"},
{chinese:"猎人",type:"nom",word:"der Jäger",plural:"die Jäger",example:"Sein Vater war Jäger"},
{chinese:"蒙古的",type:"adj",word:"mongolisch",example:"Das ist eine mongolische Volkssage"},
{chinese:"民间传说",type:"nom",word:"die Volkssage",plural:"die Volkssagen",example:"Das ist eine schöne Volkssage"},
{chinese:"打猎",type:"inf",word:"jagen",example:"In der Freizeit jagt sein Vater"},
{chinese:"邻里关系",type:"nom",word:"die Nachbarschaft",plural:"die Nachbarschaften",example:"In der Nachbarschaft ist er berühmt für seine Freundlichkeit"},
{chinese:"蛇",type:"nom",word:"die Schlange",plural:"die Schlangen",example:"Die kleine Schlange ist weiß"},
{chinese:"绕道",type:"nom",word:"der Umweg",plural:"die Umwege",example:"Hier ist ein Baustelle. man soll den Umweg machen"},
{chinese:"瞬间",type:"nom",word:"der Augenblick",plural:"die Augenblicke",example:"In disem Augenblick ist dieser Unfall passiert"},
{chinese:"飞走",type:"trennV",word:"hinweg/fliegen",example:"Der Kranich fliegt über meinen Kopf hinweg"},
{chinese:"鹤",type:"nom",word:"der Kranich",plural:"die Kraniche",example:"Ein Kranich ist eine Art von Vogeln"},
{chinese:"抓住",type:"inf",word:"ergreifen",example:"Sie ergreift diese Gelegenheit"},
{chinese:"射击，射伤",type:"inf",word:"schießen",example:"Er schießt in die Luft"},
{chinese:"飞走",type:"trennV",word:"davon/fiegen",example:"Der Vogel flog davon"},
{chinese:"龙王",type:"nom",word:"der Drachenkönig",plural:"die Drachenkönige",example:"Der Drachenkönig war nett"},
{chinese:"宝石",type:"nom",word:"der Edelstein",plural:"die Edelsteine",example:"Das ist ein echter Edelstein"},
{chinese:"保存，收藏",type:"trennV",word:"auf/bewahren",example:"Er hat ihren Brief gut aufbewahrt"},
{chinese:"变成",type:"inf",word:"verwandeln",example:"Das Dorf hat sich in eine kleine Stadt verwandelt"},
{chinese:"告别，离别",type:"nom",word:"der Abschied",plural:"die Abschiede",example:"Sie nehmen Abschied von uns"},
{chinese:"有成就的",type:"adj",word:"erfolgreich",example:"Er hat die Prüfung erfolgreich bestanden"},
{chinese:"洪水",type:"nom",word:"das Hochwasser",example:"Er herrschte hier Hochwasser"},
{chinese:"拯救",type:"inf",word:"retten",example:"Sie hat ihm das Leben gerettet"},
{chinese:"山巅，山顶",type:"nom",word:"der Berggipfel",example:"Auf diesem Berggipfel gibt es viel Schnee"},
];
const B2E5 = [
{chinese:"金融中心",type:"nom",word:"das Finanzzentrum",plural:"die Finanzzentren",example:"Frankfurt ist ein wichtiges Finanzzentrum in Deutschland"},
{chinese:"作曲家",type:"nom",word:"der Komponist",plural:"die Komponisten",example:"Mozart war ein berühmter Konponist"},
{chinese:"从前的，以前的",type:"adj",word:"ehemalig",example:"Heute habe ich einen ehemaligen Freund besucht"},
{chinese:"汽车工业的先驱",type:"nom",word:"der Automobilpionier",plural:"die Automibilpioniere",example:"Carl Benz war ein Automobilpionier"},
{chinese:"汽车城",type:"nom",word:"die Automobilstadt",plural:"die Automobilstädte",example:"Stuttgart ist eine Automobilstadt"},
{chinese:"著名的",type:"adj",word:"berühmt",example:"Berlin ist eine berühmte Stadt"},
{chinese:"莱比锡",type:"nom",word:"Leipzig",plural:"o.Pl",example:"Leipzig ist eine große Stadt"},
{chinese:"中止，暂停",type:"inf",word:"unterbrechen",example:"Er unterbricht seine Reise und fährt nach Hause zurück"},
{chinese:"斯特拉登堡",type:"nom",word:"Straßburg",plural:"o.Pl",example:"Straßburg ist eine Französische Stadt"},
{chinese:"继续",type:"trennV",word:"fort/setzen",example:"Diese Arbeit kann ich morgen schon fortsetzen"},
{chinese:"从……起",type:"präp",word:"ab",example:"Ab zehnten Juli haben wir Sommerferien"},
{chinese:"公务员",type:"nom",word:"der Beamte",plural:"d.w.adj",example:"Sein Vater war Beamter"},
{chinese:"著作，工厂",type:"nom",word:"das Werk",plural:"die Werke",example:",,Faust'' war ein großes Werk von Goethe"},
{chinese:"世界著名的",type:"adj",word:"weltberühmt",example:"Das Buch ist weltberühmt"},
{chinese:"出生的城市",type:"die Geburtsstadt",word:"die Geburtsstädte",example:"Shaoxing ist die Geburtsstadt von Luxun"},
{chinese:"联邦银行",type:"nom",word:"die Bundesband",plural:"o.Pl",example:"Die Bundesbank befindet sich in Frankfurt"},
{chinese:"中央银行",type:"nom",word:"die Zentralbank",plural:"die Zentralbanken",example:"Die Zentralbank der EU hat ihren Sitz in Frankfurt a.M.."},
{chinese:"所在地，座位",type:"nom",word:"der Sitz",plural:"die Sitze",example:"Viele große Firmen haben ihren Sitz in dieser Stadt"},
{chinese:"证券交易所",type:"nom",word:"die Börse",plural:"die Börsen",example:"Die größte Börse Deutschlands befindet sich in Frankfurt a.M."},
{chinese:"商业银行",type:"nom",word:"die Geschäftsbank",plural:"die Geschäftsbanken",example:"Ist die Deutsche Bank eine Geschäftsbank?"},
{chinese:"出生于，源自",type:"trennV",word:"stammen/aus",example:"Er stammt aus München/stammen von"},
{chinese:"音乐之家",type:"nom",word:"die Musikerfamilie",plural:"die Musikerfamilien",example:"Er stammt aus einer Musikerfamilie"},
{chinese:"神童",type:"nom",word:"das Wunderkind",plural:"die Wunderkinder",example:"Mozart war ein Wunderkind"},
{chinese:"获得，得到",type:"inf",word:"erhalten",example:"Heute habe ich ein Geschenk erhalten"},
{chinese:"登台，出场",type:"trennV",word:"treten/auf",example:"Mit zehn Jahren trat er schon auf"},
{chinese:"出版，发表",type:"inf",word:"veröffentlichen",example:"Im letzten Jahr hat er einen Roma veröffentlicht"},
{chinese:"作曲，谱曲",type:"nom",word:"die Komposition",plural:"die Kompositionen",example:"Er versteht sehr viel von der Komposition"},
{chinese:"公开的，公共的",type:"adj",word:"öffentlich",example:"Ich benutze oft öffentliche Verkehrsmittel, wenn ich zur Arbeit fahre"},
{chinese:"声望，尊重",type:"nom",word:"das Ansehen",plural:"o.Pl",example:"Der Dichter hat ein hohes Ansehen gewonnen"},
{chinese:"赢得，获得",type:"inf",word:"gewinnen",example:"Wir haben den Wettkampf gewonnen"},
{chinese:"忍受……煎熬",type:"trennV",word:"leiden/an",example:"Sein Vater hat lange Zeit an einer schweren Krankheit gelitten/leiden unter"},
{chinese:"听力衰弱",type:"nom",word:"die Hörschwäche",plural:"o.Pl",example:"Er leidet an Hörschwäche und kann nicht gut hören"},
{chinese:"聋的，听不见的",type:"adj",word:"taub",example:"Der alte Mann ist taub und kann nichts hören"},
{chinese:"留下，遗留",type:"inf",word:"hinterlassen",example:"Sein Vater hat ihn ein Haus hinterlassen"},
{chinese:"交响乐，交响曲",type:"nom",word:"die Sinfonie",plural:"die Sinfonien",example:"Die neue Sinfonie von Beethoven gefällt mir sehr gut"},
{chinese:"统一，联合",type:"nom",word:"die Vereinigung",plural:"die Vereinigungen",example:"Nach der Vereinigung Deutschlands ist er nach Dresden gezogen"},
{chinese:"重要性",type:"nom",word:"die Bedeutung",plural:"die Bedeutungen",example:"Diese Stadt ist für mir von großer Bedeutung"},
{chinese:"服务性行业中心，第三产业中心",type:"nom",word:"das Dienstleistungszentrum",plural:"die Dienstleistungszentren",example:"Diese Stadt ist eins der Dienstleistungszentrum des Landes"},
{chinese:"科学中心",type:"nom",word:"das Wissenschaftszentrum",plural:"die Wissenschaftszentren",example:"Man aht die Stadt zu einem Wissenschaftszentrum ausgebaut"},
{chinese:"自然科学的",type:"adj",word:"naturwissenschaftlich",example:"Er hat großes Interesse für naturwissenschaftliche Fragen"},
{chinese:"经验",type:"nom",word:"die Erfahrung",plural:"die Erfahrungen",example:"Beim Praktikum könne die Studenten viele Erfahrungen machen"},
{chinese:"机械制造业",type:"nom",word:"die Maschinenbauindustrie",plural:"die Maschinenindustrien",example:"Die Maschinenbauindustrie hat sich schnell entwickelt"},
{chinese:"建立，创立",type:"inf",word:"gründen",example:"Man hat vor 100 Jahren die Firma gegründet"},
{chinese:"企业",type:"nom",word:"das Unternehmen",plural:"die Unternehmen",example:"Die Firma ist ein privates Unternehmen"},
{chinese:"奉献",type:"inf",word:"widmen",example:"Er hat sich der Wissenschaft gewidmet/widmen sich D"},
{chinese:"车辆，交通工具",type:"nom",word:"das Fahrzeug",plural:"die Fahrzeugen",example:"Man kann mit verschiedenen Fahrzeugen in die Stadt fahren"},
{chinese:"马",type:"nom",word:"das Pferd",plural:"die Pferde",example:"Er ist vom Pferd gefallen"},
{chinese:"用汽油作燃料的汽车",type:"nom",word:"das Benzinauto",plural:"die Benzinautos",example:"Carl Benz hat das erste Benzinauto der Welt gebaut"},
{chinese:"三轮的",type:"adj",word:"dreirädrig",example:"Heute kann man kaum noch dreirädrige Wagen sehen"},
{chinese:"第一次，初次",type:"adv",word:"erstmals",example:"Er ist erstmals hier"},
{chinese:"发明，创造",type:"nom",word:"die Erfindung",plural:"die Erfindungen",example:"Er hat in seinem Leben viele Erfindungen gemacht"},
{chinese:"改变，更改",type:"inf",word:"verändern",example:"Seine Erfindung hat das Leben der Menschen verändert"},
{chinese:"制造者，生产者",type:"nom",word:"der Hersteller",plural:"die Hersteller",example:"Wer ist der Hersteller dieses Fahrrads"},
{chinese:"窄小的，紧密的",type:"adj",word:"eng",example:"Wir arbeiten eng zusammen"},
{chinese:"另一方面",type:"adv",word:"andererseits",example:"Einerseits möchte er gern uns besuchen, andererseits muss er die Arbeit erledigen"},
{chinese:"属于，算作",type:"inf",word:"zählen zu",example:"Er zählt zu dem besten Studenten der Klasse"},
{chinese:"在……中间，在……当中",type:"adv",word:"inmitten von",example:"Die Familie saß im Gerten, inmitten von Blumen und Bäumen"},
{chinese:"葡萄园",type:"nom",word:"der Weinberg",plural:"die Weinberge",example:"Auf der Zugfahrt am Rhein haben wir viele Weinberge gesehen"},
{chinese:"绿化地带",type:"nom",word:"die Grünanlage",plural:"die Grünanlagen",example:"In dieser Stadt hat man viele Grünanlagen gebaut"},
{chinese:"安静，安宁",type:"nom",word:"die Ruhe",plural:"o.Pl",example:"Am Wochenende möchte er nur seine Ruhe haben"},
{chinese:"修养，休息，复元",type:"nom",word:"die Erholung",plural:"die Erholungen",example:"Nach einer guten Erholung kann mann besser arbeiten"},
{chinese:"发展，研发",type:"inf",word:"entwickeln",example:"In den letzten Jahren hat sich China schnell entwickelt"},
{chinese:"午夜，子夜",type:"nom",word:"die Mitternacht",plural:"o.Pl",example:"Nach Mitternacht fährt kein Bus mehr"},
{chinese:"说明，陈述",type:"nom",word:"die Angabe",plural:"die Angaben",example:"Der Kollege hat genaue Angabe über seine Arbeit gemacht"},
{chinese:"港口",type:"nom",word:"der Hafen",plural:"die Häfene",example:"Shanghai hat einen großen Hafen"},
{chinese:"私人的",type:"adj",word:"privat",example:"Ich schreibe einen privaten Brief"},
{chinese:"三千年的",type:"adj",word:"dreitausendjährig",example:"Die Stadt hat eine dreitausendjährige Geschichte"},
{chinese:"根据，基于",type:"präp",word:"aufgrund",example:"Aufgrund des schlechten Wetters könne wir nicht spazieren gehen"},
{chinese:"文化宝藏",type:"nom",word:"der Kulturschatz",plural:"die Kulturschätze",example:"In China gibt es viele Kulturschätze"},
{chinese:"名胜古迹",type:"nom",word:"die Sehenswürdigkeit",plural:"die Sehenswürdigkeiten",example:"Wir haben viele Sehenswürdigkeiten besucht"},
{chinese:"官邸",type:"nom",word:"die Residenz",plural:"die Residenzen",example:"Das war die Residenz des Kaisers"},
{chinese:"用于，作……用",type:"trennV",word:"dienen",example:"Das Zimmer dient als Esszimmer"},
{chinese:"皇帝的，帝王的",type:"adj",word:"kaiserlich",example:"Beijing ist eine kaiserliche Stadt"},
{chinese:"大都市",type:"nom",word:"die Metropole",plural:"die Metropolen",example:"Die Stadt ist eine Metropole der Kunst"},
{chinese:"歌剧院",type:"nom",word:"die Oper",plural:"die Opern",example:"Heute Abend gehen wir in die Oper"},
{chinese:"文化",type:"nom",word:"die Kultur",plural:"die Kulturen",example:"Er interessiert sich sehr für chinesische Kultur"},
{chinese:"周围，环境",type:"nom",word:"die Umgebung",plural:"die Umgebungen",example:"In der Umgebung gibt es eine große Bibliothek"},
{chinese:"赞赏，惊叹",type:"inf",word:"bewundert",example:"Ich habe seine Fortschritte sehr bewundert"},
{chinese:"历史的",type:"adj",word:"historisch",example:"Das ist eine historische Frage"},
{chinese:"胡同,巷子",type:"nom",word:"die Gasse",plural:"die Gassen",example:"In der Innenstadt gibt es viele Gassen"},
{chinese:"传统的",type:"adj",word:"traditionell",example:"Traditionelle Kleidung gefällt mir"},
{chinese:"内院，内廷",type:"nom",word:"der Innenhof",plural:"Innenhöfe",example:"In Beijing gibt es immer wenige Häuser mit Innenhöfen"},
{chinese:"地区，地带",type:"nom",word:"die Gegend",plural:"die Gegenden",example:"Wir sind durch die schönsten Gegend des Landes gefahren"},
{chinese:"藏传佛教寺庙",type:"nom",word:"der Lamatempel",plural:"die Lamatempel",example:"Wie haben ein Lamatempel besichtigt"},
{chinese:"人力车",type:"nom",word:"die Rikscha",plural:"die Rikscha",example:"Wir sind mit einer Rikscha durch die Gassen fahren"},
{chinese:"妻子",type:"nom",word:"die Ehefrau",plural:"die Ehefrauen",example:"Seine Ehefrau ist Ärztin"},
{chinese:"作者，作家",type:"nom",word:"der Autor",plural:"die Autoren",example:"Wer ist der Autor des Buches"},
{chinese:"一百年，世纪",type:"nom",word:"das Jahrhundert",plural:"die Jahrhunderte",example:"Im letzten Jahrhundert hat das Land viel verändert"},
{chinese:"举办地，承办地",type:"nom",word:"der Austragungsort",plural:"die Austragungsorte",example:"Beijing ist der Ausdtragungsort für die Olympischen Spiele 2008"},
{chinese:"国家体育场",type:"nom",word:"das Nationalstation",plural:"die Nationalstationen",example:"Das Spiel findet im Nationalstation statt"},
{chinese:"所谓的",type:"adj",word:"sogenannt",example:"Er darf seinem sogenannten Freund nicht glauben"},
{chinese:"新颖的，独特的",type:"adj",word:"originell",example:"Ich finde diese Idee sehr originell"},
{chinese:"建筑方式",type:"nom",word:"die Bauweise",plural:"o.Pl",example:"Die Bauweise des Hauses gefällt mir"},
{chinese:"建筑丰碑",type:"nom",word:"das Architekturdenkmal",plural:"die Architekturdenkmäler",example:"In dieser Stadt kann man viele Architekturdenkmäler sehen"},
{chinese:"吸引",type:"trennV",word:"an/ziehen",example:"Die schöne Stadt zieht viele Touristen an"},
{chinese:"令人着迷的",type:"adj",word:"faszinierend",example:"China ist ein faszinierendes Land"},
{chinese:"生长",type:"nom",word:"das Wachstum",plural:"o.Pl",example:"Er bewundert das Schnelle Wachstum der Stadt"},
];
const B2E6 = [
{chinese:"新闻，消息",type:"nom",word:"die Nachricht",plural:"die Nachrichten",example:"Ich lese jeden Tag Nachrichten"},
{chinese:"了解，查询，获悉",type:"inf",word:"informieren",example:"Er möchte sich über das Land informieren/ sich über etw informieren"},
{chinese:"网页",type:"nom",word:"die Webseite",plural:"die Webseiten",example:"Haben Sie eine Webseite im Internet?"},
{chinese:"工作",type:"nom",word:"der Job",plural:"die Jobs",example:"Ich suche in den Ferien einen Job."},
{chinese:"使用",type:"inf",word:"benutzen",example:"Ich habe bei der Übersetzung des Textes ein Wörterbuch benutzt"},
{chinese:"有意义的",type:"adj",word:"sinvoll",example:"Das ist eine Sinnvolle Arbeit"},
{chinese:"事物，东西",type:"nom",word:"das Ding",plural:"die Dinge",example:"Wissen Sie, wie das Ding auf Deutsch heißt?"},
{chinese:"有帮助的",type:"adj",word:"hilfreich",example:"Der Computer ist hilfreich für meine Arbeit"},
{chinese:"职业上的",type:"adj",word:"beruflich",example:"Was macht er beruflich?"},
{chinese:"工作职位",type:"nom",word:"die Arbeitsstelle",plural:"die Arbeitsstellen",example:"Er hat eine gute Arbeitsstelle"},
{chinese:"数小时的",type:"adj",word:"stundenlang",example:"Er sitzt stundenlang vor dem Computer und spielt"},
{chinese:"一起",type:"adv",word:"miteinander",example:"Wir arbeiten miteinander"},
{chinese:"下载",type:"trennV",word:"herunter/laden",example:"Ich habe heute schöne Bilder heruntergeladen"},
{chinese:"排除在外的",type:"adj",word:"ausgeschlossen",example:"Er ist von dieser Arbeit ganz ausgeschlossen"},
{chinese:"(电流)打开",type:"trennV",word:"ein/schalten",example:"Er schaltet den Fernseher ein und sieht fern"},
{chinese:"(电流)关闭",type:"trennV",word:"aus/schalten",example:"Schalten Sie bitte das Licht aus, wenn Sie weggehen"},
{chinese:"程序，节目，计划",type:"no",word:"das Program",plural:"die Programe",example:"Er hat angefangen, ein neues Programm zu schreiben"},
{chinese:"安装，装设",type:"inf",word:"installieren",example:"Ich muss ein neues Programm installieren"},
{chinese:"资料，数据",type:"nom",word:"die Datei",plural:"die Dateien",example:"Mann muss die wichtigen Dateien gut speichern"},
{chinese:"编辑，处理，加工",type:"inf",word:"bearbeiten",example:"Ich habe den Bericht geschrieben und muss ihn bearbeiten"},
{chinese:"开始",type:"trennV",word:"los/gehen",example:"Das Fussballspiel geht um sechs Uhr los"},
{chinese:"把……放进去",type:"trennV",word:"rein/legen",example:"Legen Sie bitte die CD rein"},
{chinese:"消除，清楚",type:"inf",word:"löschen",example:"Ich habe den Text gelöscht"},
{chinese:"储存",type:"inf",word:"speichern",example:"Ich habe die Informationen in den Computer gespeichert"},
{chinese:"点击鼠标",type:"nom",word:"der Mausklick",plural:"die Mausklicke",example:"Das geht ganz einfach. Nur ein Mausklick. Dann klappt alles"},
{chinese:"调用(数据)，取用(信息)",type:"nom",word:"der Abruf",plural:"o.Pl",example:"Wir könne jeder Zeit hilfreiche Informationen per Abruf aus Internet bekommen"},
{chinese:"结果，成果，成绩",type:"nom",word:"das Ergebnis",plural:"die Ergebnisse",example:"Bei der Letzten Prüfung hat er ein gutes Ergebnis bekommen"},
{chinese:"调用，取用",type:"trennV",word:"ab/rufen",example:"Man kann zahlreiche Informationen über deutsche Städte abrufen"},
{chinese:"将……打印，打印出来",type:"trennV",word:"aus/drucken",example:"Ich habe ein schönes Bild heruntergeladen und ausgedruckt"},
{chinese:"电脑专家",type:"nom",word:"der Computerfachmann",plural:"die Computerfachleute",example:"Er ist Computerfachmann und versteht viel vom Computer"},
{chinese:"地图",type:"nom",word:"die Landkarte",plural:"die Landkarten",example:"Hast du eine Landkarte von Deutschland?"},
{chinese:"劳动局，劳工局",type:"nom",word:"das Arbeitsamt",plural:"die Arbeitsämter",example:"Er geht zum Arbeitsamt und sucht dort eine Arbeitsstelle"},
{chinese:"机器",type:"nom",word:"die Maschine",plural:"die Maschinen",example:"Was kann man mit dieser Maschine machen?"},
{chinese:"装置，器械，仪器",type:"nom",word:"der Apparat",plural:"die Apparate",example:"Ich kann leider nicht fotografieren. Der Apparat ist kaputt"},
{chinese:"活动，工作",type:"nom",word:"die Tätigkeit",plural:"die Tätigkeiten",example:"Er hat eine interessante Tätigkeit gefunden"},
{chinese:"节约，储蓄，节省",type:"inf",word:"sparen",example:"Es ist wichtig für uns, Wasser zu sparen"},
{chinese:"够，足够",type:"adj",word:"genug",example:"Ich wollte in den Ferien eine Reise in Deutschland machen, hatte aber nicht genug Geld dafür"},
{chinese:"飞行员",type:"nom",word:"der Pilot",plural:"die Piloten",example:"Es war sein Traum, Pilot zu werden"},
{chinese:"电子的",type:"adj",word:"elektronisch",example:"In dem Laden werden elektronische Geräte verkauft"},
{chinese:"印刷的",type:"adj",word:"gedruckt",example:"Ich lese lieber gedruckte Bücher"},
{chinese:"不断增长的",type:"adj",word:"zunehmend",example:"Die Umweltveschmutzung ist ein zunehmendes Problem"},
{chinese:"年龄组",type:"nom",word:"die Altersgruppe",plural:"die Altersgruppen",example:"Verschiedene Altersgruppen haben an der Umfrage teilgenommen"},
{chinese:"学徒",type:"nom",word:"der Lehrling",plural:"die Lehrlinge",example:"Die Lehrlinge sind Leute, die gerade eine Lehre machen"},
{chinese:"印刷",type:"nom",word:"die Auflage",plural:"die Auflagen",example:"Das ist schon die 5. Auflage des Buches"},
{chinese:"一方面",type:"adv",word:"einerseits",example:"Einerseites lernt er in der Berufsschule, andererseits macht er Praktikum bei einer Firma"},
{chinese:"搜索功能",type:"nom",word:"die Suchfunktion",plural:"o.Pl",example:"Ich benutze oft die Suchfunktion des Computers"},
{chinese:"占优势的，胜过，强于",type:"adj",word:"überlegen",example:"Die neue Maschine ist der alten überlegen"},
{chinese:"引文，引语",type:"nom",word:"das Zitat",plural:"die Zitate",example:"Er hat einige Zitate für den Text genommen"},
{chinese:"使容易，减轻",type:"inf",word:"erleichtern",example:"Die Arbeit wird durch Machine erleichtert"},
{chinese:"特别的，特殊的，专门的",type:"adj",word:"speziell",example:"Für diese Arbeit braucht man ein spezielles Gerät"},
{chinese:"必要的",type:"adj",word:"notwendig",example:"Er ist uns notwendig, viele Übungen zu machen"},
{chinese:"袖珍本",type:"nom",word:"das Taschenbuch",plural:"die Taschenbücher",example:"Er nimmt immer ein Taschenbuch mit, wenn er reist"},
{chinese:"数字的",type:"adj",word:"digital",example:"In diesem Laden werden digitale Geräte verkauft"},
{chinese:"储存器",type:"nom",word:"der Speicher",plural:"die Speicher",example:"Das Lesegerät hat einen Speicher"},
{chinese:"配备有……的",type:"adj",word:"ausgestattet",example:"Das Labor ist mit modernen Geräten ausgestattet"},
{chinese:"内容",type:"nom",word:"der Inhalt",plural:"die Inhalte",example:"Ich kann den Inhalt des Textes nicht verstehen"},
{chinese:"转录，转存",type:"inf",word:"überspielen",example:"Ich möchte die Musik auf mein neues Gerät überspielen"},
{chinese:"显示器",type:"nom",word:"das Display",plural:"die Displays",example:"Mann kann auf dem Display Texte lesen"},
{chinese:"上面",type:"nom",word:"die Oberseite",plural:"die Oberseiten",example:"Auf der Oberseite sehe ich ein Bild"},
{chinese:"位于，处于",type:"inf",word:"befinden",example:"Wo befindet die Stadtbibliothek?"},
{chinese:"顾客，客户",type:"der Kunde",word:"die Kunden",example:"Er ist ein alter Kunde des Kaufhauses"},
{chinese:"续买",type:"trennV",word:"nach/kaufen",example:"Man kann elektronische Bücher nachkaufen"},
{chinese:"联合，统一",type:"inf",word:"vereinen",example:"Wir können unsere Meinungen nicht vereinen"},
{chinese:"强项，特长",type:"nom",word:"die Stärke",plural:"die Stärken",example:"Schwimmen ist seine Stärke"},
{chinese:"优点，好处",type:"nom",word:"der Vorteil",plural:"die Vorteile",example:"Es gibt Vorteile, wenn man in der Stadtmitte wohnt"},
{chinese:"抗，背，拉",type:"inf",word:"schleppen",example:"Ich muss einen großen Koffer schleppen, wenn ich eine große Reise mache"},
{chinese:"装入，打包",type:"trennV",word:"ein/packen",example:"Ich habe das Geschenk eingepackt"},
{chinese:"推广，流行，传播",type:"nom",word:"die Verbreitung",plural:"die Verbreitungen",example:"Man hat Angst vor einer schnellen Verbreitung dieser Krankheit"},
{chinese:"便宜的，物美价廉的",type:"adj",word:"preiswert",example:"Auf diesem Markt kann man preiswert kaufen"},
];
const B2E7 = [
{chinese:"女护士",type:"nom",word:"die Krankenschwester",plural:"die Krankenschwestern",example:"Meine Tante ist Krankenschwester"},
{chinese:"机动车机械师，机动车机械工",type:"nom",word:"der Kfz-Mechaniker, die Kfz-Mechaniker",example:"Mein Bruder ist Kfz-Mechaniker"},
{chinese:"旅游团",type:"nom",word:"die Reisegruppe",plural:"die Reisegruppen",example:"Sie begleitet die Reisegruppe nach Beijing"},
{chinese:"修理",type:"inf",word:"reparieren",example:"Er repariert die Uhr"},
{chinese:"生意，商店",type:"nom",word:"das Geschäft",plural:"die Geschäfte",example:"Mein Bruder macht gute Geschäfte"},
{chinese:"商务人员",type:"nom",word:"der Bürokaufmann",plural:"die Bürokaufleute",example:"Er will Bürokaufmann werden"},
{chinese:"轻松的，容易的",type:"adj",word:"leicht",example:"Deutsch ist nicht so leicht"},
{chinese:"车间",type:"nom",word:"die Werkstatt",plural:"die Werkstätten",example:"Sein Vater hat ein Autowerkstatt"},
{chinese:"接受，接管",type:"inf",word:"übernehmen",example:"Ich freue mich sehr, wenn du diese Aufgabe übernehmen kannst"},
{chinese:"尽管，即使",type:"konj",word:"obwohl",example:"Obwohl er krank ist, kommt er noch"},
{chinese:"脏的",type:"adj",word:"schmutzig",example:"Die Jacke ist schmutzig"},
{chinese:"累的，疲劳的",type:"adj",word:"anstrengend",example:"Diese lange Reise ist sehr anstrengend"},
{chinese:"规定",type:"nom",word:"die Vorschrift",plural:"die Vorschriften",example:"Man soll sich an die Vorschrifften halten"},
{chinese:"专心致志的",type:"adj",word:"konzentriert",example:"Er arbeitet konzentriert am Computer"},
{chinese:"文理中学毕业考试",type:"nom",word:"das Abitur",plural:"die Abiture",example:"Annette macht im nächsten Jahr das Abitur"},
{chinese:"实验中学",type:"nom",word:"die Realschule",plural:"die Realschulen",example:"Hans besucht nun die Realschule"},
{chinese:"倒班制工作",type:"nom",word:"die Schichtarbeit",plural:"o.Pl",example:"Peter muss Schichtarbeit machen"},
{chinese:"反对",type:"adv",word:"dagegen",example:"Ich bin ganz dagegen"},
{chinese:"决定，确定",type:"inf",word:"bestimmen",example:"Er kann seinen Beruf selbst bestimmen"},
{chinese:"幸运，运气",type:"nom",word:"das Glück",plural:"o.Pl",example:"Sie hat Glück, ihre Geldtasche wieder gefunden zu haben"},
{chinese:"职业学校",type:"nom",word:"die Berufsschule",plural:"die Berufschulen",example:"Nach der Berufsschule arbeitet er als Mechaniker in einer Autowerkstatt"},
{chinese:"理论山的",type:"adj",word:"theoretisch",example:"In der Berufsschule bekommt er theoretischen Unterricht"},
{chinese:"求职信",type:"nom",word:"die Bewerbung",plural:"die Bewerbungen",example:"Sie hat viele Bewerbungen geschrieben, um eine bessere Stelle zu finden"},
{chinese:"幸运地",type:"adv",word:"glücklicherweise",example:"Glücklicherweise habe ich den Zug noch erreicht"},
{chinese:"旅行社",type:"nom",word:"das Reisebüro",plural:"die Reisebüros",example:"Das Reisebüro heißt Panda"},
{chinese:"贸易公司",type:"die Handelsfirma",word:"die Handelsfirmen",example:"Sein Bruder arbeitet bei einer Handelsfirma"},
{chinese:"尽管如此",type:"adv",word:"trotzdem",example:"Sie ist krank, trotzdem will sie noch ausgehen"},
{chinese:"商务出差",type:"nom",word:"die Geschäftsreise",plural:"die Geschäftsreisen",example:"Er macht morgen eine Geschäftsreise"},
{chinese:"归来",type:"nom",word:"die Rückkehr",plural:"o.Pl",example:"Nach der Rückkehr aus Deutschland arbeitet er bei VW in Shanghai"},
{chinese:"从事，做",type:"inf",word:"unternehmen",example:"Sie ist sehr müde und will nicht unternehmen"},
{chinese:"现在的",type:"adj",word:"jetzig",example:"Sie will die jetzige Stelle aufgeben"},
{chinese:"段落，章节",type:"nom",word:"der Abschnitt",plural:"die Abschnitte",example:"Lesen Sie den srsten Abschnitt"},
{chinese:"满意度",type:"nom",word:"die Zufriedenheit",plural:"o.Pl",example:"Mit Zufiredenheit nimmt er diese neue Stelle an"},
{chinese:"职业选择",type:"nom",word:"die Berufswahl",plural:"die Berufswahlen",example:"Welche Wünsche hast du bei der Berufswahl"},
{chinese:"公务出差",type:"nom",word:"die Dienstreise",plural:"die Dienstreisen",example:"Er macht oft Dienstreisen"},
{chinese:"加班",type:"nom",word:"die Überstunde",plural:"die Überstunden",example:"Ich muss immer Überstunden machen"},
{chinese:"独立的",type:"adj",word:"selbstständig",example:"Thomas ist ein selbstständiger Mensch"},
{chinese:"工作环境",type:"nom",word:"das Arbeitsklima",example:"Das Arbeitsklima dort gefällt ihr nicht"},
{chinese:"幸福的, 开心的",type:"adj",word:"glücklich",example:"Sie hat ein glückliches Leben"},
{chinese:"尽管, 不顾",type:"prap",word:"trotz",example:"Trotz der Krankheit ist sie noch zur Arbeit gegangen"},
{chinese:"强大的，厉害的",type:"adj",word:"stark",example:"Ich habe starke Kopfschmerzen"},
{chinese:"电流",type:"nom",word:"der Strom",plural:"die Ströme",example:"Schalten Sie den Strom aus"},
{chinese:"开(灯)",type:"trennV",word:"an/machen",example:"Mach das Licht an"},
{chinese:"手套",type:"nom",word:"der Handschuh",plural:"die Handschuhe",example:"Wo sind meine Handschuhe"},
{chinese:"检查，检验",type:"inf",word:"prüfen",example:"Prüfen Sie die Maschine"},
{chinese:"关掉, 放下, 停放",type:"trennV",word:"ab/stellen",example:"Stellen Sie das Gas ab"},
{chinese:"工具",type:"nom",word:"das Werkzeug",plural:"die Werkzeuge",example:"Stellen Sie  dieses Werkzeug in die Ecke"},
{chinese:"关掉(灯)， 总计",type:"trennV",word:"aus/machen",example:"Machen Sie bitte das Licht aus"},
{chinese:"锁上，结束",type:"trennV",word:"ab/schließen",example:"Schliß die Tür ab"},
{chinese:"忙的",type:"adj",word:"beschäftigt",example:"Sie ist zurzeit beschäftigt mit der Prüfung"},
{chinese:"兴趣",type:"nom",word:"das Iteresse",plural:"o.Pl",example:"Das Kind hat großes Interesse am Zeichnen"},
{chinese:"多次",type:"adv",word:"mehrmals",example:"Ich habe ihm mehrmals gemailt"},
{chinese:"矛盾, 异议",type:"nom",word:"der Wiederspruch",plural:"die Wiedersprüche",example:"Es besteht ein Wiederspruch zwischen seinem Reden und Handeln"},
{chinese:"然而，不过",type:"adv",word:"allerdings",example:"Ich komme gern, allerdings möchte ich erst morgen kommen"},
{chinese:"从业愿望",type:"nom",word:"der Berufswunsch",plural:"die Berufswünsche",example:"Welchen Berufswunsch hast du, Peter?"},
{chinese:"广播电台",type:"nom",word:"der Rundfunk",plural:"o.Pl",example:"Ihre Schwester arbeitet beim Rundfunk"},
{chinese:"听众",type:"nom",word:"der Hörer",plural:"die Hörer",example:"Liebe Hörerinnen und Hörer, heute wollen wir Ihnen eine echte Geschichte erzählen"},
{chinese:"女主持人",type:"nom",word:"die Moderatorin",plural:"die Moderatorinnen",example:"Seine Freundin arbeitet als Moderatorin beim Rundfunk"},
{chinese:"播送，广播",type:"nom",word:"die Sendung",plural:"die Sendungen",example:"Wann fängt heute die Sendung an?"},
{chinese:"受欢迎的",type:"adj",word:"willkommen",example:"Wir heißen Sie willkommen in Nanjing"},
{chinese:"播音室，演播室",type:"nom",word:"das Studio",plural:"die Studios",example:"Wir sind ins Studio zur Sendung eingeladen worden"},
{chinese:"德国高级文理中学",type:"nom",word:"das Gymnasium",plural:"die Gymnasien",example:"Gabi besucht nächstes Jahr das Gymnasium"},
{chinese:"医学，药",type:"nom",word:"die Medizin",plural:"die Medizinen",example:"Sein Bruder studiert Medizin"},
{chinese:"任务，作业",type:"nom",word:"die Aufgabe",plural:"die Aufgaben",example:"Er hat zurzeit viele Aufgaben"},
{chinese:"结束",type:"nom",word:"der Abschluss",plural:"die Abschlüsse",example:"Nach dem Studienabschluss arbeitet er bei Siemens"},
{chinese:"学徒的学习期",type:"nom",word:"die Lehre",plural:"die Lehren",example:"Er hat seine Lehre von drei Jahren gemacht"},
{chinese:"企业营销人员",type:"nom",word:"der Industriekaufmann",plural:"die Industriekaufleute",example:"Nach der Berufsschule arbeitet er als Industriekaufmann"},
{chinese:"但愿",type:"adv",word:"hoffentlich",example:"Hoffentlich wird das Wetter morgen schön bleiben"},
{chinese:"希望，前途",type:"nom",word:"die Absicht",plural:"die Absichten",example:"Er meint, wenn man Informatik studiert, hat man gute Aussichten"},
{chinese:"经济部门",type:"nom",word:"der Wirschaftszweig",plural:"die Wirtschaftszweige",example:"Man braucht Informatiker in vielen Wirtschaftzweigen"},
{chinese:"教会",type:"trennV",word:"bei/bringen",example:"Sie bringt den Kindern das Lesen bei"},
{chinese:"设想，介绍",type:"nom",word:"die Vorstellung",plural:"die Vorstellungen",example:"Jetzt kommen die Vorstellung"},
{chinese:"双元的",type:"adj",word:"dual",example:"In Deutschland führt man das duale System durch"},
{chinese:"签订",type:"inf",word:"unterschreiben",example:"Er hat einen Mietsvertrag mit der Vermieterin unterschrieben"},
{chinese:"培训合同，协议",type:"nom",word:"der Ausbildungsvertrag",plural:"die Ausbildungsverträge",example:"Hans schließt einen Ausbildungsvertrag mit einem Betrieb ab"},
{chinese:"企业",type:"nom",word:"der Betrieb",plural:"die Betriebe",example:"Sie arbeitet in diesem Betrieb."},
{chinese:"学徒，接受培训的人",type:"nom",word:"der Auszubildende",plural:"die Auszubildenden",example:"Peter ist nun ein Auszubildender"},
{chinese:"理论，原理",type:"die Theorie",word:"die Theorien",example:"Man soll die Theorie und Praxis verbinden"},
{chinese:"实施，实行",type:"trennV",word:"durch/führen",example:"Wann führt man dieses Program durch"},
{chinese:"集中上课",type:"nom",word:"der Blockunterricht",plural:"o.Pl",example:"In der Ausbildungsschule wird Blockunterricht durchgeführt"},
{chinese:"剩余的",type:"adj",word:"restlich",example:"Man hat Blockunterricht in der Ausbildungsschule und arbeiter in der restlichen Zeit im Betrieb"},
{chinese:"社会学",type:"nom",word:"die Sozialkunde",plural:"o.Pl",example:"Sein Bruder studiert Sozialkunde"},
{chinese:"厨师(女)",type:"nom",word:"die Köchin",plural:"die Köchinnen",example:"Ihre Tante ist Köchin"},
{chinese:"中期考试",type:"nom",word:"die Zwischenprüfung",plural:"die Zwischenprüfungen",example:"Am nächsten Freitag haben wir eine Zwischenprüfung"},
{chinese:"毕业考试",type:"nom",word:"die Abschlussprüfung",plural:"die Abschlussprüfungen",example:"Wann findet die Abschlussprüfung statt"},
{chinese:"证明，成绩单",type:"nom",word:"das Zeugnis",plural:"die Zeugnisse",example:"Er hat ein gutes Zeugnis in Physik bekommen"},
{chinese:"培养，训练",type:"trennV",word:"aus/bilden",example:"Sie bildet ihre Stimme aus"},
{chinese:"费用",type:"nom",word:"die Kosten",plural:"die Kosten",example:"Wer trägt die Kosten?"},
{chinese:"企业的",type:"adj",word:"betrieblich",example:"Wann findet die betriebliche Ausbildung statt?"},
{chinese:"悬而未决",type:"trennV",word:"offen/bleiben",example:"Die Frage ist noch offengeblieben"},
];
const B2E8 = [
{chinese:"(大学讨论课)",type:"nom",word:"das Seminar",plural:"die Seminare",example:"Morgen habe ich ein Seminar bei Professor Wolf"},
{chinese:"教室",type:"nom",word:"der Unterrichtsraum",plural:"die Unterrichtsräume",example:"Wir haben Physikunterricht in diesem Unterrichtsraum"},
{chinese:"阶梯教室",type:"nom",word:"der Hörsaal",plural:"die Hörsäle",example:"Die Studenten haben Vorlesungen im Hörsaal"},
{chinese:"转变，转换",type:"nom",word:"die Umwandlung",plural:"die Umwandlungen",example:"Es gibt eine große Umwandlung im deutschen Hochschulsystem"},
{chinese:"研究生学习",type:"nom",word:"der Magisterstudiengang",plural:"die Magisterstudiengänge",example:"Welchen Magisterstudiengang hast du gewählt?"},
{chinese:"本科学位",type:"nom",word:"der Bachelor",plural:"die Bachelor",example:"Er hat seinen Bachelor in Mathematik erhalten"},
{chinese:"硕士学习",type:"nom",word:"der Master",plural:"die Master",example:"Sie hat seinen Master in Germanistik erhalten"},
{chinese:"变化",type:"nom",word:"die Veränderung",plural:"die Veränderungen",example:"Die Stadt Nanjing hat eine große Veränderung"},
{chinese:"照顾，照管",type:"inf",word:"betreuen",example:"Sie betreut einen Alten Kranken"},
{chinese:"缩短",type:"inf",word:"verkürzen",example:"Die Arbeitszeit ist jeden Tag eine Stunde verkürzt worden"},
{chinese:"可比性",type:"nom",word:"die Vergleichbarkeit",plural:"die Vergleichbaikeiten",example:"Es gibt keine Vergleichbarkeit zwischen den beiden Dingen"},
{chinese:"认可，承认",type:"nom",word:"die Anerkennung",plural:"die Anerkennungen",example:"Er findet die Anerkennung von seinem Chef"},
{chinese:"标准，准则",type:"nom",word:"der Maßstab",plural:"die Maßstäbe",example:"Du kannst die beiden Dingen nicht mit demselben Maßstab messen"},
{chinese:"学期",type:"nom",word:"das Semester",plural:"die Semester",example:"Das neuer Semester beginnt"},
{chinese:"需要，要求",type:"inf",word:"erforden",example:"Diese Arbeit erfordert viel Zeit"},
];
